name: Build dev
on:
  workflow_call:
    inputs:
      tag:
        type: string
        default: ${{ github.ref_name }}
        description: A version to checkout
    outputs:
      tag:
        value: ${{ inputs.tag }}
  workflow_dispatch:
    tags:
      - "*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  dev:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
          fetch-tags: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: save tag version
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push UTasksFront
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .ops/old.Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/marketalerts/utf:${{ inputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
