name: Build and generate prod version tag

on:
  workflow_call:
    outputs:
      tag:
        value: v${{ jobs.production.outputs.version }}
        description: A new version tag generated via npm
      version:
        value: ${{ jobs.production.outputs.version }}
        description: A new package version as seen in package.json, generated via npm

jobs:
  production:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.current-version }}

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "a.raiondesu@gmail.com"

    - run: npm ci --omit=optional -w utf
    - run: npm i --no-save cross-env

    - name: Read SemVer
      uses: actions-ecosystem/action-release-label@955bf130fba6be3d99d2c14457d0dc7f176bc563
      id: release

    - name: Read package.json
      uses: martinbeentjes/npm-get-version-action@v1.3.1
      id: package

    - name: Release
      run: npm run ${{ steps.release.outputs.level }}

    - name: Save new version
      uses: martinbeentjes/npm-get-version-action@v1.3.1
      id: version

    - run: npm run build

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.4
      with:
        message: ${{ steps.version.outputs.current-version }}
        tag: 'v${{ steps.version.outputs.current-version }}'

    - name: Push
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GIT_PAT }}
        branch: main
